-- SQL Practice: Food Delivery Database
-- Custom questions and answers for practice
-- Schema:
--   customer (id, name, email, city, join_date, premium)
--   restaurant (id, name, city, cuisine, rating, delivery_time_mins)
--   menu_item (id, restaurant_id, name, category, price, is_available)
--   order (id, customer_id, restaurant_id, order_date, status, total_amount)
--   order_item (order_id, menu_item_id, quantity, unit_price)
--   delivery (id, order_id, driver_id, pickup_time, delivery_time, distance_km)
--   driver (id, name, city, rating, total_deliveries)
--   review (id, customer_id, restaurant_id, rating, comment, review_date)

-- ============================================================
-- SECTION 1: Basic SELECT and WHERE
-- ============================================================

-- Q1. Show all restaurants in Delhi
SELECT * FROM restaurant
WHERE city = 'Delhi';

-- Q2. Show all menu items under ₹200
SELECT name, price, category FROM menu_item
WHERE price < 200
ORDER BY price ASC;

-- Q3. Show all orders that were cancelled
SELECT * FROM order
WHERE status = 'cancelled';

-- Q4. Show restaurants with rating above 4.5
SELECT name, cuisine, rating FROM restaurant
WHERE rating > 4.5
ORDER BY rating DESC;

-- Q5. Show all available vegetarian menu items
-- (assuming category 'Veg' means vegetarian)
SELECT name, price FROM menu_item
WHERE category = 'Veg'
AND is_available = 1
ORDER BY price ASC;

-- ============================================================
-- SECTION 2: Aggregation (SUM, COUNT, AVG, GROUP BY, HAVING)
-- ============================================================

-- Q6. How many restaurants are there in each city?
SELECT city, COUNT(id) AS restaurant_count
FROM restaurant
GROUP BY city
ORDER BY restaurant_count DESC;

-- Q7. What is the average order value for each restaurant?
SELECT restaurant.name, ROUND(AVG(order.total_amount), 2) AS avg_order_value
FROM restaurant
JOIN order ON restaurant.id = order.restaurant_id
WHERE order.status = 'delivered'
GROUP BY restaurant.name
ORDER BY avg_order_value DESC;

-- Q8. What is the total revenue generated by each cuisine type?
SELECT restaurant.cuisine, SUM(order.total_amount) AS total_revenue
FROM order
JOIN restaurant ON order.restaurant_id = restaurant.id
WHERE order.status = 'delivered'
GROUP BY restaurant.cuisine
ORDER BY total_revenue DESC;

-- Q9. Which drivers have completed more than 100 deliveries?
SELECT name, total_deliveries, rating FROM driver
WHERE total_deliveries > 100
ORDER BY total_deliveries DESC;

-- Q10. Which restaurants have received more than 50 reviews?
SELECT restaurant.name, COUNT(review.id) AS review_count,
       ROUND(AVG(review.rating), 2) AS avg_rating
FROM restaurant
JOIN review ON restaurant.id = review.restaurant_id
GROUP BY restaurant.name
HAVING COUNT(review.id) > 50
ORDER BY review_count DESC;

-- ============================================================
-- SECTION 3: JOIN
-- ============================================================

-- Q11. Show each order with customer name, restaurant name and total amount
SELECT customer.name AS customer, restaurant.name AS restaurant,
       order.order_date, order.total_amount, order.status
FROM order
JOIN customer ON order.customer_id = customer.id
JOIN restaurant ON order.restaurant_id = restaurant.id
ORDER BY order.order_date DESC;

-- Q12. Show all menu items ordered by customers from Mumbai
SELECT DISTINCT menu_item.name, menu_item.price
FROM menu_item
JOIN order_item ON menu_item.id = order_item.menu_item_id
JOIN order ON order_item.order_id = order.id
JOIN customer ON order.customer_id = customer.id
WHERE customer.city = 'Mumbai';

-- Q13. Show each delivery with driver name, distance and delivery time
SELECT driver.name AS driver,
       delivery.distance_km,
       TIMESTAMPDIFF(MINUTE, delivery.pickup_time, delivery.delivery_time) AS delivery_mins
FROM delivery
JOIN driver ON delivery.driver_id = driver.id
ORDER BY delivery_mins DESC;

-- Q14. Show all customers who have ordered from Italian restaurants
SELECT DISTINCT customer.name, customer.city
FROM customer
JOIN order ON customer.id = order.customer_id
JOIN restaurant ON order.restaurant_id = restaurant.id
WHERE restaurant.cuisine = 'Italian';

-- Q15. Show the most ordered menu item from each restaurant
SELECT restaurant.name, menu_item.name AS item, SUM(order_item.quantity) AS total_ordered
FROM restaurant
JOIN menu_item ON restaurant.id = menu_item.restaurant_id
JOIN order_item ON menu_item.id = order_item.menu_item_id
GROUP BY restaurant.name, menu_item.name
ORDER BY restaurant.name, total_ordered DESC;

-- ============================================================
-- SECTION 4: Subqueries
-- ============================================================

-- Q16. Show restaurants with above average rating
SELECT name, city, rating FROM restaurant
WHERE rating > (SELECT AVG(rating) FROM restaurant)
ORDER BY rating DESC;

-- Q17. Show customers who have never placed an order
SELECT name, email FROM customer
WHERE id NOT IN (
    SELECT DISTINCT customer_id FROM order
);

-- Q18. Show the highest spending customer in each city
SELECT city, name, total_spent
FROM (
    SELECT customer.city, customer.name,
           SUM(order.total_amount) AS total_spent
    FROM customer
    JOIN order ON customer.id = order.customer_id
    WHERE order.status = 'delivered'
    GROUP BY customer.city, customer.name
) AS spending
WHERE total_spent = (
    SELECT MAX(total_spent_inner)
    FROM (
        SELECT customer.city AS cty,
               SUM(order.total_amount) AS total_spent_inner
        FROM customer
        JOIN order ON customer.id = order.customer_id
        WHERE order.status = 'delivered'
        GROUP BY customer.city, customer.name
    ) AS inner_spending
    WHERE inner_spending.cty = spending.city
);

-- Q19. Show drivers with above average rating
SELECT name, rating, total_deliveries FROM driver
WHERE rating > (SELECT AVG(rating) FROM driver)
ORDER BY rating DESC;

-- Q20. Show restaurants that have never received a 1-star review
SELECT name FROM restaurant
WHERE id NOT IN (
    SELECT DISTINCT restaurant_id FROM review
    WHERE rating = 1
)
ORDER BY name;
